---
issues:
  exclude-rules:
    - path: tools/tables.go
      linters:
        - dupl
linters:
  enable-all: true
  disable:
    - depguard
    - exhaustivestruct
    - exhaustruct
    - forbidigo
    - gci
    - gochecknoglobals
    - goerr113
    - gofumpt
    - gomnd
    - ifshort
    - nlreturn
    - noctx
    - paralleltest
    - testpackage
    - varnamelen
linters-settings:
  revive:
    rules:
      - name: unused-parameter
        disabled: true
run:
  tests: false
