---
name: QA
on:
  push:
jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Install dependencies
        run: |
          make golangci-lint
          pip install yamllint==1.26.*
      - name: Check
        run: |
          make lint
          make yamllint
