---
name: QA
on:
  push:
jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Install dependencies
        run: |
          pip install yamllint==1.26.*
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.60.3
      - name: Check
        run: |
          make yamllint
