---
name: Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        job:
          - arch: amd64
            os: darwin
          - arch: arm64
            os: darwin
          - arch: amd64
            os: linux
          - arch: arm64
            os: linux
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Install dependencies
        run: |
          sudo go run main.go upx
      - name: Build
        env:
          BINARY: staticd-${{ matrix.job.os }}-${{ matrix.job.arch }}
          GOARCH: ${{ matrix.job.arch }}
          GOOS: ${{ matrix.job.os }}
        run: |
          make build
      - name: UPX
        if: matrix.job.os != 'darwin'
        run: |
          make upx
      - uses: actions/upload-artifact@v2
        with:
          path: dist/
          name: dist
  release:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: dist/
          name: dist
      - uses: softprops/action-gh-release@v1
        if: contains(github.ref, '-rc')
        with:
          files: |
            dist/staticd-darwin-amd64
            dist/staticd-darwin-arm64
            dist/staticd-linux-amd64
            dist/staticd-linux-arm64
          prerelease: true
      - uses: softprops/action-gh-release@v1
        if: contains(github.ref, '-rc') == false
        with:
          files: |
            dist/staticd-darwin-amd64
            dist/staticd-darwin-arm64
            dist/staticd-linux-amd64
            dist/staticd-linux-arm64
