---
name: Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        job:
          - arch: amd64
            os: darwin
          - arch: amd64
            os: linux
          - arch: arm
            os: linux
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Install dependencies
        run: |
          wget https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz
          sudo tar -C /usr/local/bin/ -xf upx-3.96-amd64_linux.tar.xz --strip 1 upx-3.96-amd64_linux/upx
      - name: Build
        env:
          BINARY: staticd-${{ matrix.job.os }}-${{ matrix.job.arch }}
          GOARCH: ${{ matrix.job.arch }}
          GOOS: ${{ matrix.job.os }}
        run: |
          make build
          make upx
      - uses: actions/upload-artifact@v2
        with:
          path: dist/
          name: dist
  release:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: dist/
          name: dist
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/staticd-darwin-amd64
            dist/staticd-linux-amd64
            dist/staticd-linux-arm
